using System.Text;
using Chronos.Master.Application.Abstractions;
using Microsoft.Extensions.Logging;

namespace Chronos.Master.Infrastructure.Proxy;

/// <summary>
/// Writes YAML fragments consumed by Traefik &lt;code&gt;providers.file&lt;/code&gt;.
/// Mount the same directory Traefik watches (e.g. shared Docker volume).
/// </summary>
public sealed class TraefikFileReverseProxyConfigurator : IReverseProxyConfigurator
{
    private readonly string _directory;
    private readonly ILogger<TraefikFileReverseProxyConfigurator> _logger;

    public TraefikFileReverseProxyConfigurator(string directory, ILogger<TraefikFileReverseProxyConfigurator> logger)
    {
        _directory = directory;
        _logger = logger;
    }

    public Task UpsertHttpRouteAsync(
        string routeName,
        string rule,
        IReadOnlyList<string> backendUrls,
        CancellationToken cancellationToken = default)
    {
        Directory.CreateDirectory(_directory);
        var safeName = Sanitize(routeName);
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Chronos.Master — Traefik file provider fragment");
        sb.AppendLine("http:");
        sb.AppendLine("  routers:");
        sb.AppendLine($"    chronos_{safeName}:");
        sb.AppendLine($"      rule: \"{EscapeYaml(rule)}\"");
        sb.AppendLine($"      service: chronos_svc_{safeName}");
        sb.AppendLine("      entryPoints:");
        sb.AppendLine("        - web");
        sb.AppendLine("  services:");
        sb.AppendLine($"    chronos_svc_{safeName}:");
        sb.AppendLine("      loadBalancer:");
        sb.AppendLine("        servers:");
        foreach (var url in backendUrls)
            sb.AppendLine($"          - url: \"{EscapeYaml(url.TrimEnd('/'))}\"");

        var path = Path.Combine(_directory, $"chronos-route-{safeName}.yml");
        File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
        _logger.LogInformation("Traefik dynamic route written: {Path}", path);
        return Task.CompletedTask;
    }

    public Task RemoveRouteAsync(string routeName, CancellationToken cancellationToken = default)
    {
        var safeName = Sanitize(routeName);
        var path = Path.Combine(_directory, $"chronos-route-{safeName}.yml");
        if (File.Exists(path))
        {
            File.Delete(path);
            _logger.LogInformation("Traefik dynamic route removed: {Path}", path);
        }

        return Task.CompletedTask;
    }

    private static string Sanitize(string name)
    {
        var chars = name.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray();
        return new string(chars);
    }

    private static string EscapeYaml(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
