namespace Chronos.Core.Compose.Interfaces;

/// <summary>
/// Fluent builder for a full Docker Compose project: YAML generation, local runs, agent publish, cluster deploy, and volume operations.
/// </summary>
public interface IComposeBuilder
{
    IComposeBuilder WithVersion(string version);
    IComposeBuilder WithComposeFilePath(string composeFilePath);
    IComposeBuilder WithProjectName(string projectName);
    IComposeBuilder WithDockerComposeExecutable(string dockerComposeExecutable);
    IComposeBuilder WithDockerComposeV2();

    IComposeBuilder AddService(Service service);
    IComposeBuilder AddService(Action<IServiceBuilder> configure);

    IComposeBuilder AddNetwork(Network network);
    IComposeBuilder AddNetwork(string name, string driver = "bridge");
    IComposeBuilder AddVolume(Volume volume);
    IComposeBuilder AddVolume(string name, string driver = "local");
    IComposeBuilder AddSecret(Secret secret);
    IComposeBuilder AddConfig(Config config);
    IComposeBuilder AddExtension(string key, object value);

    /// <summary>Ship a file next to compose on the agent (packed into a tar upload on publish).</summary>
    IComposeBuilder AddDeployArtifactFromFile(string deployRelativePath, string sourceFilePath, int? unixFileMode = null);

    /// <summary>Ship a directory tree under <paramref name="deployRelativePath"/>.</summary>
    IComposeBuilder AddDeployArtifactFromDirectory(string deployRelativePath, string sourceDirectoryPath, int? unixFileMode = null);

    ProjectManifest BuildManifest();
    string SerializeManifestJson();
    bool HasManifestPayload();
    IReadOnlyList<DeployArtifact> GetDeployArtifacts();

    string GenerateYaml();
    Task SaveToFileAsync(string path, CancellationToken cancellationToken = default);
    Task<ValidationResult> ValidateAsync(ComposeValidatorOptions? options = null, CancellationToken cancellationToken = default);

    Task<TestResult> StartAsync(
        string composeFilePath,
        string projectName,
        string dockerComposeExecutable,
        TestOptions? options = null,
        CancellationToken cancellationToken = default);

    Task<TestResult> StartAsync(TestOptions? options = null, CancellationToken cancellationToken = default);

    Task StopAsync(
        string composeFilePath,
        string projectName,
        bool removeVolumes = false,
        string dockerComposeExecutable = "auto",
        CancellationToken cancellationToken = default);

    Task StopAsync(bool removeVolumes, CancellationToken cancellationToken = default);
    Task StopAsync(CancellationToken cancellationToken = default);

    Task<TestResult> TestAsync(
        string composeFilePath,
        string projectName,
        string dockerComposeExecutable,
        TestOptions? options = null,
        CancellationToken cancellationToken = default);

    Task<TestResult> TestAsync(TestOptions? options = null, CancellationToken cancellationToken = default);

    Task<DeployResult> PublishAsync(string agentUrl, string? apiKey = null, CancellationToken cancellationToken = default);

    /// <summary>Deploy compose through Chronos.Master (smart agent selection).</summary>
    Task<ClusterDeployResult> DeployToClusterAsync(
        string masterUrl,
        string? apiKey = null,
        string? preferredLocation = null,
        CancellationToken cancellationToken = default);

    /// <summary>Publish compose + manifest through Chronos.Master.</summary>
    Task<ClusterDeployResult> PublishToClusterAsync(
        string masterUrl,
        string? apiKey = null,
        string? preferredLocation = null,
        CancellationToken cancellationToken = default);

    Task PushManifestAndArtifactsAsync(string agentUrl, string? apiKey = null, CancellationToken cancellationToken = default);

    /// <summary>Stream volume snapshot from agent to a local file (docker stdout → tar, low RAM use).</summary>
    Task SnapshotRemoteVolumeToFileAsync(
        string agentUrl,
        string dockerVolumeName,
        string localFilePath,
        string? apiKey = null,
        string compress = "gzip",
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Convenience overload: stores snapshot into "./snapshots" with autogenerated filename.
    /// Returns full path to created file.
    /// </summary>
    Task<string> SnapshotRemoteVolumeToFileAsync(
        string agentUrl,
        string dockerVolumeName,
        string? apiKey = null,
        string compress = "gzip",
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Stream volume snapshot from agent to a local directory and auto-generate file name.
    /// Returns full created file path.
    /// </summary>
    Task<string> SnapshotRemoteVolumeToDirectoryAsync(
        string agentUrl,
        string dockerVolumeName,
        string localDirectoryPath,
        string? apiKey = null,
        string compress = "gzip",
        string? filePrefix = null,
        CancellationToken cancellationToken = default);

    Task<VolumeOperationResult> SnapshotRemoteVolumeUploadToUrlAsync(
        string agentUrl,
        string dockerVolumeName,
        VolumeSnapshotUploadRequest request,
        string? apiKey = null,
        CancellationToken cancellationToken = default);

    Task<VolumeOperationResult> RestoreRemoteVolumeFromFileAsync(
        string agentUrl,
        string dockerVolumeName,
        string localArchivePath,
        string? apiKey = null,
        string compress = "gzip",
        CancellationToken cancellationToken = default);

    Task<VolumeOperationResult> RestoreRemoteVolumeFromUrlAsync(
        string agentUrl,
        string dockerVolumeName,
        VolumeRestoreFromUrlRequest request,
        string? apiKey = null,
        CancellationToken cancellationToken = default);

    Task<DeployResult> StartRemoteAsync(string agentUrl, string? apiKey = null, CancellationToken cancellationToken = default);
    Task<DeployResult> RestartRemoteAsync(string agentUrl, string? apiKey = null, CancellationToken cancellationToken = default);
    Task<DeployResult> StopRemoteAsync(string agentUrl, string? apiKey = null, bool removeVolumes = false, CancellationToken cancellationToken = default);

    /// <summary>Best-effort C# fluent reconstruction.</summary>
    string ToFluentApiCode(string variableName = "compose");
}
