// <auto-generated />
using System;
using Chronos.Master.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chronos.Master.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChronosMasterDbContext))]
    partial class ChronosMasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chronos.Master.Domain.Entities.ArchivedProjectEntity", b =>
                {
                    b.Property<string>("ArchiveId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("archive_id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("agent_url");

                    b.Property<DateTimeOffset>("ArchivedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_utc");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("project_name");

                    b.Property<DateTimeOffset>("PurgeAfterUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purge_after_utc");

                    b.HasKey("ArchiveId");

                    b.HasIndex("ProjectName");

                    b.HasIndex("PurgeAfterUtc");

                    b.ToTable("archived_projects", (string)null);
                });

            modelBuilder.Entity("Chronos.Master.Domain.Entities.AuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_ip");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("result");

                    b.Property<DateTimeOffset>("UtcTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("utc_time");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Chronos.Master.Domain.Entities.LeaderLeaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AcquiredUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_utc");

                    b.Property<string>("HolderInstanceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("holder_instance_id");

                    b.Property<DateTimeOffset>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until_utc");

                    b.HasKey("Id");

                    b.ToTable("leader_lease", (string)null);
                });

            modelBuilder.Entity("Chronos.Master.Domain.Entities.ProjectPlacementEntity", b =>
                {
                    b.Property<string>("ProjectName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("project_name");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("agent_url");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("ProjectName");

                    b.ToTable("project_placements", (string)null);
                });

            modelBuilder.Entity("Chronos.Master.Domain.Entities.RegisteredAgentEntity", b =>
                {
                    b.Property<string>("AgentId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("agent_id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("base_url");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("capabilities_json");

                    b.Property<double?>("CpuPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("cpu_percent");

                    b.Property<double?>("DiskPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("disk_percent");

                    b.Property<DateTimeOffset>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_utc");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("location");

                    b.Property<double?>("MemoryPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("memory_percent");

                    b.Property<DateTimeOffset>("RegisteredUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_utc");

                    b.HasKey("AgentId");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("Chronos.Master.Domain.Entities.VolumeBackupPolicyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("ExtraKeyPrefix")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("extra_key_prefix");

                    b.Property<int>("MaxCooldownMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("max_cooldown_minutes");

                    b.Property<int>("MaxCopies")
                        .HasColumnType("integer")
                        .HasColumnName("max_copies");

                    b.Property<int>("MinCopies")
                        .HasColumnType("integer")
                        .HasColumnName("min_copies");

                    b.Property<int>("MinMinutesBetweenBackups")
                        .HasColumnType("integer")
                        .HasColumnName("min_minutes_between_backups");

                    b.Property<int?>("MinimumFreeDiskMb")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_free_disk_mb");

                    b.Property<int>("MinutesCooldownPerGb")
                        .HasColumnType("integer")
                        .HasColumnName("minutes_cooldown_per_gb");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("project_name");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<string>("VolumeNamePattern")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("volume_name_pattern");

                    b.HasKey("Id");

                    b.HasIndex("ProjectName");

                    b.ToTable("volume_backup_policies", (string)null);
                });

            modelBuilder.Entity("Chronos.Master.Domain.Entities.VolumeBackupStateEntity", b =>
                {
                    b.Property<string>("ProjectName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("project_name");

                    b.Property<string>("VolumeName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("volume_name");

                    b.Property<long?>("LastApproxBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("last_approx_bytes");

                    b.Property<DateTimeOffset?>("LastBackupUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_backup_utc");

                    b.HasKey("ProjectName", "VolumeName");

                    b.ToTable("volume_backup_state", (string)null);
                });

            modelBuilder.Entity("Chronos.Master.Domain.Entities.VolumePlacementEntity", b =>
                {
                    b.Property<string>("ProjectName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("project_name");

                    b.Property<string>("VolumeName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("volume_name");

                    b.Property<string>("AgentId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("agent_id");

                    b.Property<long?>("BytesUsed")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_used");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("ProjectName", "VolumeName", "AgentId");

                    b.ToTable("volume_placements", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
